name: fleather_mention
description: "Mentions for the Fleather rich text editor"
version: 0.0.1
homepage: https://github.com/Amir-P/fleather_mention
repository: https://github.com/Amir-P/fleather_mention

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fleather: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0